import { Suspense } from 'react';
import { promises as fs } from 'fs';
import path from 'path';
import { StrandWithTweet } from '@/lib/types';
import { BestStrandsClient } from './BestStrandsClient';

// Pre-baked strands data with seed tweets (generated by strands.py)
const STRANDS_DATA_PATH = path.join(process.cwd(), 'public/strands_data.json');

interface StrandsData {
  generatedAt: string;
  count: number;
  strands: StrandWithTweet[];
}

async function loadStrands(): Promise<StrandWithTweet[]> {
  try {
    const data = await fs.readFile(STRANDS_DATA_PATH, 'utf-8');
    const parsed: StrandsData = JSON.parse(data);
    return parsed.strands;
  } catch (e) {
    console.error('Failed to load strands_data.json:', e);
    return [];
  }
}

export default async function BestStrandsPage() {
  const strands = await loadStrands();

  if (strands.length === 0) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p>No strands found. Run `python strands.py --export-only` to generate data.</p>
      </div>
    );
  }

  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center">Loading strands...</div>}>
      <BestStrandsClient strands={strands} />
    </Suspense>
  );
}
